\\ Copyright (C) 2026 Marcello Federico
\\ SPDX-License-Identifier: GPL-3.0-or-later
\\
\\ This file is part of the fermat433 proof record
\\ <https://github.com/marchfederico/fermat433>.  It is free software: you may
\\ redistribute it and modify it under the terms of the GNU General Public
\\ License, either version 3 of the License or (at your option) any later
\\ version.  It is distributed WITHOUT ANY WARRANTY.  See the LICENSE file at
\\ the repository root, or <https://www.gnu.org/licenses/>.

\\ Fake 2-Selmer group of J = Jac(y^2 = f(x)), f irreducible of degree 6 over Q (Stoll 2001; Bruin-Stoll 2009).
\\ Global: H_Q(S) = {a in L(S,2) : N(a) square}/Q(S,2), S = SPRIMES (all primes dividing 2 disc(f), plus any others wanted);
\\ L(S,2) is obtained from S'-units, S' = S + primes whose classes generate the 2-part of Cl(L), with the even-valuation
\\ condition re-imposed at the extra primes.  Local at p in S: image of J(Q_p)/2J(Q_p) under x - theta, generated by Q_p-
\\ and quadratic points, in Hilbert-symbol coordinates w.r.t. a basis of L_P^*/L_P^*2 for each P | p; at the real place
\\ the sign vectors.  Output: dim of the fake Selmer group F and dim Sel^2(J) = dim F + [L has no quadratic subfield]
\\ (valid when X has points everywhere locally, e.g. X(Q) nonempty).
default(parisize, "2G"); default(parisizemax, "8G");
read("curve_input.gp");
\\ ---------- global setup
clorder(cols, cyc) = if (#cyc == 0, 1, my(M = if (#cols == 0, matdiagonal(cyc), matconcat([matconcat(cols), matdiagonal(cyc)]))); abs(matdet(mathnf(M))));
setup(fpol) = {
  my(P0, red, cyc, cols, q, dl, ord);
  f = fpol; c = pollead(f); P0 = c^5 * subst(f, x, y/c);
  red = polredbest(P0, 1); P = red[1]; th = red[2] / c;
  if (subst(f, x, th) != 0, error("theta is not a root of f"));
  bnf = bnfinit(P, 1); cyc = bnf.cyc;
  print("L = Q[y]/(", P, "), signature ", bnf.sign, ", class group ", cyc, ", index of the model ", factor(poldisc(P) / bnf.disc)[,1]~);
  \\ extra primes whose prime ideals generate the class group modulo an odd-order quotient
  SEXTRA = []; cols = [];
  foreach (SPRIMES, p, foreach (idealprimedec(bnf, p), pr, cols = concat(cols, [bnfisprincipal(bnf, pr, 0)])));
  ord = clorder(cols, cyc); q = 2;
  while (ord % 2 == 0, q = nextprime(q + 1); if (vecsearch(vecsort(SPRIMES), q) || bnf.disc % q == 0, next);
    foreach (idealprimedec(bnf, q), pr, cols = concat(cols, [bnfisprincipal(bnf, pr, 0)])); SEXTRA = concat(SEXTRA, [q]); ord = clorder(cols, cyc));
  SALL = concat(SPRIMES, SEXTRA);
  print("S = ", SPRIMES, "  extra primes for the class group: ", SEXTRA, "  (odd part of Cl left: ", ord, ")");
  S = concat(apply(p -> idealprimedec(bnf, p), SALL));
  su = bnfsunit(bnf, S);
  gens = concat(concat(bnf.fu, [bnf.tu[2]]), su[1]);   \\ ordering used by bnfissunit: fundamental units, torsion, S-units
  NM = matrix(#gens, 1 + #SALL, i, j, my(n = nfeltnorm(bnf, gens[i]), an = abs(n)); if (j == 1, n < 0, valuation(an, SALL[j-1]) % 2));
  for (i = 1, #gens, my(an = abs(nfeltnorm(bnf, gens[i]))); foreach (SALL, q, an /= q^valuation(an, q)); if (an != 1, error("norm outside S")));
  K = lift(matker(Mod(mattranspose(NM), 2)));
  QS = matrix(#gens, 1 + #SALL, i, j, my(e = bnfissunit(bnf, su, concat([-1], SALL)[j])); if (e == 0 || #e != #gens, error("not an S-unit")); lift(Mod(e[i], 2)));
  for (j = 1, 1 + #SALL, my(q = concat([-1], SALL)[j], e = bnfissunit(bnf, su, q), pr = Mod(1, P)); for (i = 1, #gens, pr *= Mod(lift(gens[i]) * Mod(1, P), P)^lift(e[i])); if (pr != q, error(Str("S-unit exponent ordering mismatch at q = ", q))));
  my(Bq = Mod(QS, 2), rq = matrank(Bq), Fb = List());
  for (i = 1, #K, my(M = matconcat([Bq, matconcat(Vec(Fb)), Mod(K[,i], 2)])); if (matrank(M) > rq + #Fb, listput(Fb, Mod(K[,i], 2))));
  Fglob = apply(v -> lift(v), Vec(Fb));
  print("#gens L(S',2) = ", #gens, ", norm-square dim ", #K, ", Q(S',2) image dim ", rq, ", dim H_Q(S') = ", #Fglob);
  Fel = vector(#Fglob, i, my(a = Mod(1, P)); for (j = 1, #gens, if (Fglob[i][j], a *= Mod(lift(gens[j]) * Mod(1, P), P))); a);
  QSUB = #select(v -> poldegree(v[1]) == 2, nfsubfields(bnf, 2));
  Fel; };
\\ ---------- Hilbert-symbol coordinates at a prime pr of L
hb(a, b, pr) = (nfhilbert(bnf, lift(a), lift(b), pr) == -1);
mkbasis(pr) = { my(m = 2 + (pr.p == 2) * pr.e * pr.f, cands = List(), sel = List(), H, G, unif, ee, jmax);
  listput(cands, Mod(nfbasistoalg(bnf, pr.gen[2]), P)); foreach ([-1, 2, 3, 5, 7, 11, 13], q, listput(cands, Mod(q, P)));
  for (k = -6, 6, listput(cands, Mod(y + k, P)); listput(cands, Mod(y^2 + k, P)); listput(cands, Mod(y^2 + k*y + 1, P)); listput(cands, Mod(y^3 + k, P)));
  for (t = 1, 160, listput(cands, Mod(sum(i = 0, 5, (random(7) - 3) * y^i), P)));
  unif = Mod(nfbasistoalg(bnf, pr.gen[2]), P); ee = pr.e; jmax = 2*ee + 3;
  for (j = 1, jmax, foreach ([1, y, y + 1, y^2 + 1, y^2 + y + 1, y^3 + 1], u, listput(cands, 1 + unif^j * Mod(u, P))));
  cands = select(cc -> cc != 0, Vec(cands));
  H = Mod(matrix(#cands, #cands, a, b, hb(cands[a], cands[b], pr)), 2);
  if (matrank(H) != m, error(Str("candidates span ", matrank(H), " of ", m, " dimensions at a prime above ", pr.p)));
  for (i = 1, #cands, if (#sel >= m, break); my(rows = concat(Vec(sel), [i]), Mr = matrix(#rows, #cands, a, b, H[rows[a], b])); if (matrank(Mr) > #sel, listput(sel, i)));
  G = Mod(matrix(m, m, a, b, H[sel[a], sel[b]]), 2);
  [vector(m, i, cands[sel[i]]), G^(-1)]; };
coords(a, B) = { my(sel = B[1], Ginv = B[2], h = Mod(vectorv(#sel, j, hb(a, sel[j], pr_cur)), 2)); lift(Ginv * h); };
resv(a, p) = { my(v = []); for (k = 1, #PR[p], pr_cur = PR[p][k]; v = concat(v, Vec(coords(a, BAS[p][k])))); vectorv(#v, i, v[i]); };
\\ product-formula check of the local symbols (the 2-adic ones are the delicate ones)
realsym(a, b) = { my(sa = nfeltsign(bnf, lift(a)), sb = nfeltsign(bnf, lift(b)), s = 1); for (i = 1, #sa, if (sa[i] < 0 && sb[i] < 0, s = -s)); s; };
prodcheck(ntests) = { my(bad = 0);
  for (t = 1, ntests, my(a = Mod(sum(i = 0, 5, (random(9) - 4) * y^i), P), b = Mod(sum(i = 0, 5, (random(9) - 4) * y^i), P), s, pl);
    if (a == 0 || b == 0, next);
    s = realsym(a, b);
    pl = Set(concat([2], concat(factor(abs(nfeltnorm(bnf, a) * nfeltnorm(bnf, b)))[,1]~, factor(abs(bnf.disc))[,1]~)));
    foreach (pl, p, foreach (idealprimedec(bnf, p), pr, s *= nfhilbert(bnf, lift(a), lift(b), pr)));
    if (s != 1, bad++));
  print("product-formula check of nfhilbert on ", ntests, " random pairs: ", bad, " failures"); if (bad, error("nfhilbert inconsistent")); };
\\ ---------- local points
nonres(p) = { my(u = 2); while (kronecker(u, p) != -1, u++); u; };
issq_p(r, p) = if (r == 0, 0, issquare(r + O(p^80)));
issq_quad(A, B, d, p) = { if (B == 0, return(issq_p(A, p) || issq_p(A/d, p)));
  my(N = A^2 - d*B^2); if (N == 0 || !issq_p(N, p), return(0));
  my(m = sqrt(N + O(p^80)), t1 = (A + m)/2, t2 = (A - m)/2);
  (t1 != 0 && issquare(t1)) || (t2 != 0 && issquare(t2)); };
quadpoints(p, dlist, ulist, wlist, base, target) = { my(vecs = List(), n = 0, cur = base, rk0 = matrank(Mod(matconcat(base), 2)), rk = rk0);
  foreach (dlist, d, foreach (ulist, u, foreach (wlist, w, if (w == 0 || rk - rk0 >= target, next);
    my(fz = subst(f, x, u + w*z) % (z^2 - d), A = polcoef(fz, 0, z), B = polcoef(fz, 1, z));
    if (issq_quad(A, B, d, p), n++; my(v = resv(th^2 - 2*u*th + (u^2 - d*w^2), p), M = Mod(matconcat(concat(cur, [v])), 2));
      if (matrank(M) > rk, rk = matrank(M); cur = concat(cur, [v]); listput(vecs, v))))));
  [Vec(vecs), n, rk - rk0]; };
quadpoints_rev(p, dlist, ulist, wlist, base, target) = { my(vecs = List(), n = 0, cur = base, rk0 = matrank(Mod(matconcat(base), 2)), rk = rk0, frev = polrecip(f));
  foreach (dlist, d, foreach (ulist, u, foreach (wlist, w, if (w == 0 || rk - rk0 >= target, next);
    my(fz = subst(frev, x, u + w*z) % (z^2 - d), A = polcoef(fz, 0, z), B = polcoef(fz, 1, z));
    if (issq_quad(A, B, d, p), n++; my(v = resv(1 - 2*u*th + (u^2 - d*w^2)*th^2, p), M = Mod(matconcat(concat(cur, [v])), 2));
      if (matrank(M) > rk, rk = matrank(M); cur = concat(cur, [v]); listput(vecs, v))))));
  [Vec(vecs), n, rk - rk0]; };
localimage(p, K, jmax) = { my(vecs = List(), base = 0, n = 0, prec = 60, amax);
  for (j = 0, jmax, amax = if (p > 50, min(p^(K + j), 300), p^(K + j)); for (a = 0, amax - 1, if (j > 0 && a % p == 0, next);
    my(xt = a / p^j, fx = subst(f, x, xt)); if (fx == 0, next);
    if (!issquare(fx + O(p^prec)), next);
    my(v = resv(xt - th, p)); if (base == 0, base = v, listput(vecs, lift(Mod(v - base, 2)))); n++));
  [Vec(vecs), n]; };
\\ ---------- imposing a local condition: Sol := {b in Sol : R b in span(W)}
impose(W, R) = { my(nR = #R[,1], Wp, nW, Kall, Vp);
  Wp = if (#W == 0, matrix(nR, 0), matimage(Mod(matconcat(W), 2))); nW = #Wp;
  Kall = if (nW == 0, matker(Mod(R, 2)), matker(matconcat([Wp, Mod(R, 2)])));
  Vp = if (#Kall == 0, matrix(nF, 0), matimage(matrix(nF, #Kall, i, j, Kall[nW + i, j])));
  if (#Sol == 0 || #Vp == 0, Sol = matrix(nF, 0), my(Ki = matker(matconcat([Sol, Vp]))); Sol = if (#Ki == 0, matrix(nF, 0), matimage(Sol * Ki[1..#Sol, ])));
  #Vp; };
{
Fel = setup(FPOL); nF = #Fel; Sol = Mod(matid(nF), 2);
}
{
\\ even-valuation conditions at the extra (good) primes: valuation vector of a in span of that of q
foreach (SEXTRA, q, my(Q = idealprimedec(bnf, q), W = [vectorv(#Q, i, Q[i].e % 2)], R = matrix(#Q, nF, i, j, idealval(bnf, lift(Fel[j]), Q[i]) % 2));
  impose(W, R); print("extra prime q = ", q, ": dim of H_Q(S) candidates so far = ", #Sol));
}
{
\\ real place: sign vectors in the order of increasing real roots of f
RTH = []; for (i = 1, bnf.sign[1], RTH = concat(RTH, [real(subst(lift(th), y, bnf.roots[i]))]));
RPERM = vecsort(RTH, , 1); r1 = #RTH;
if (r1 != polsturm(f), error("real root count mismatch"));
if (r1 >= 4,
  my(k0 = (pollead(f) < 0), pts = [], W, R);
  forstep (k = k0, r1, 2, pts = concat(pts, [vectorv(r1, i, i > r1 - k)]));
  W = concat([vectorv(r1, i, 1)], vector(#pts - 1, i, pts[i + 1] - pts[1]));
  R = matrix(r1, nF, i, j, my(sg = nfeltsign(bnf, lift(Fel[j]))); sg[RPERM[i]] < 0);
  impose(W, R); print("real place (", r1, " real roots): dim of candidates so far = ", #Sol),
  print("real place (", r1, " real roots): no condition"));
}
{
PR = vector(vecmax(SPRIMES)); BAS = vector(vecmax(SPRIMES));
}
{
foreach (SPRIMES, p, PR[p] = idealprimedec(bnf, p); BAS[p] = vector(#PR[p], k, mkbasis(PR[p][k]));
  print("p = ", p, ": primes ", apply(pr -> [pr.e, pr.f], PR[p]), "  local square-class dims ", apply(B -> #B[1], BAS[p])));
prodcheck(60);
}
{
IMG = vector(vecmax(SPRIMES)); DIAG = vector(vecmax(SPRIMES));
}
{
foreach (SPRIMES, p,
  Kp = if (p == 2, 4, if (p == 3, 3, 1)); if (p > 50, Kp = 0);
  li = localimage(p, Kp, if (p > 50, 1, 2));
  Dq = if (p == 2, [-1, 2, 5], [p, nonres(p)]);
  dl = if (p == 2, [-1, 2, -2, 5, -5, 10, -10], [p, nonres(p), p*nonres(p)]);
  DIAG[p] = apply(q -> resv(Mod(q, P), p), Dq);
  sqd = select(dd -> vecmax(resv(Mod(dd, P), p)) == 0, dl);
  fa = factorpadic(f, p, 60); degs = vector(#fa[,1], ii, poldegree(fa[ii,1])); hasodd = vecmax(apply(dd -> dd % 2, degs)) == 1;
  tJ = #degs - 1 - hasodd; dJ = tJ + 2*(p == 2); oneminusone = !(hasodd || #sqd > 0);
  target = dJ - oneminusone;
  print("p = ", p, ": factors ", degs, ", dim J(Q_p)/2J(Q_p) = ", dJ, ", (1,-1)_p nonzero: ", oneminusone, " => dim of fake local image = ", target);
  base = concat(DIAG[p], li[1]); rk0 = matrank(Mod(matconcat(DIAG[p]), 2)); got = matrank(Mod(matconcat(base), 2)) - rk0;
  print("   rational points: ", li[2], ", image dim so far ", got);
  qp = [[], 0, 0];
  if (got < target,
    dep = if (p == 2, 3, 1); rng = if (p == 2, 24, min(3*p, 40));
    qp = quadpoints(p, dl, vector(2*rng*2^dep + 1, ii, (ii - 1 - rng*2^dep)/2^dep), vector(rng*2^dep, ii, ii/2^dep), base, target - got);
    got += qp[3]);
  print("   quadratic points hit: ", qp[2], ", image dim now ", got, if (got == target, "  COMPLETE", "  INCOMPLETE"));
  allv = concat(li[1], qp[1]);
  if (got < target,   \\ points near infinity: deeper denominators and the chart x = 1/u for quadratic points
    li2 = localimage(p, Kp, if (p == 2, 9, 3)); allv = concat(allv, li2[1]);
    got = matrank(Mod(matconcat(concat(DIAG[p], allv)), 2)) - rk0;
    print("   near infinity: rational points ", li2[2], ", image dim now ", got);
    if (got < target,
      dep = if (p == 2, 3, 1); rng = if (p == 2, 24, min(3*p, 40));
      qp2 = quadpoints_rev(p, dl, vector(2*rng*2^dep + 1, ii, (ii - 1 - rng*2^dep)/2^dep), vector(rng*2^dep, ii, ii/2^dep), concat(DIAG[p], allv), target - got);
      allv = concat(allv, qp2[1]); got += qp2[3];
      print("   near infinity: quadratic points hit ", qp2[2], ", image dim now ", got));
    print("   ", if (got == target, "COMPLETE", "INCOMPLETE")));
  IMG[p] = [allv, got, target]);
}
{
foreach (SPRIMES, p, my(R = matrix(#DIAG[p][1], nF, i, j, resv(Fel[j], p)[i]), W = concat(IMG[p][1], DIAG[p]), nV);
  nV = impose(W, R); print("p = ", p, ": dim V_p = ", nV, "   dim of Selmer candidates so far = ", #Sol));
}
{
COMPLETE = vector(#SPRIMES, ii, IMG[SPRIMES[ii]][2] == IMG[SPRIMES[ii]][3]);
RANKTAG = if (#TAG >= 5 && Vecsmall(TAG)[#TAG] >= 48 && Vecsmall(TAG)[#TAG] <= 57, Vecsmall(TAG)[#TAG] - 48, -1);
write("results2.txt", TAG, " dimH=", nF, " dimF=", #Sol, " complete=", COMPLETE, " quadsubfield=", QSUB, " realroots=", r1, " clgp=", bnf.cyc, " dimSel2=", #Sol + (QSUB == 0), " rank=", RANKTAG);
print("dim fake 2-Selmer group F = ", #Sol, if (vecmin(COMPLETE) == 0, "  (SOME LOCAL IMAGE INCOMPLETE: F is a lower bound)", ""), "   =>  dim Sel^2(J) = ", #Sol + (QSUB == 0), "  (fake group + ", (QSUB == 0), " for the class of [P - iota P]);  rank J(Q) <= ", #Sol + (QSUB == 0) - 0);
}
\q
