\\ Copyright (C) 2026 Marcello Federico
\\ SPDX-License-Identifier: GPL-3.0-or-later
\\
\\ This file is part of the fermat433 proof record
\\ <https://github.com/marchfederico/fermat433>.  It is free software: you may
\\ redistribute it and modify it under the terms of the GNU General Public
\\ License, either version 3 of the License or (at your option) any later
\\ version.  It is distributed WITHOUT ANY WARRANTY.  See the LICENSE file at
\\ the repository root, or <https://www.gnu.org/licenses/>.

\\ Fake 2-Selmer group of J = Jac(y^2 = f(x)), f irreducible of degree 6, following Bruin-Stoll / Stoll / Creutz.
\\ Global: F_glob = {a in L(S,2) : N(a) square}/Q(S,2).  Local at p in S: I_p = image of J(Q_p)/2J(Q_p) under x - theta,
\\ generated by Q_p-points, in coordinates given by Hilbert symbols against a basis of L_P^*/L_P^*2 for each P | p.
default(parisize, "2G"); default(parisizemax, "8G");
SPRIMES = [2, 3, 17];
setup(fpol) = {
  f = fpol; c = pollead(f); P = c^5 * subst(f, x, y/c);
  bnf = bnfinit(P, 1); th = Mod(y, P) / c;
  if (bnf.cyc != [], error("class group not trivial: L(S,2) needs class-group generators"));
  S = concat(apply(p -> idealprimedec(bnf, p), SPRIMES));
  su = bnfsunit(bnf, S);
  gens = concat([bnf.tu[2]], concat(bnf.fu, su[1]));
  \\ norm vectors over {-1, 2, 3, 17}
  NM = matrix(#gens, 4, i, j, my(n = nfeltnorm(bnf, gens[i]), v = [n < 0, valuation(abs(n), 2) % 2, valuation(abs(n), 3) % 2, valuation(abs(n), 17) % 2]);
    if (abs(n) / 2^valuation(abs(n),2) / 3^valuation(abs(n),3) / 17^valuation(abs(n),17) != 1, error("norm outside S")); v[j]);
  K = lift(matker(Mod(mattranspose(NM), 2)));            \\ columns: exponent vectors (length #gens) with square norm
  QS = matrix(#gens, 4, i, j, my(e = bnfissunit(bnf, su, [-1, 2, 3, 17][j])); if (e == 0, error("not an S-unit")); lift(Mod(e[i], 2)));
  \\ basis of F_glob = (norm-square subgroup) / (image of Q(S,2)): complement of QS-span inside K-span
  my(Bq = Mod(QS, 2), rq = matrank(Bq), Fb = List());
  for (i = 1, #K, my(M = matconcat([Bq, matconcat(Vec(Fb)), Mod(K[,i], 2)])); if (matrank(M) > rq + #Fb, listput(Fb, Mod(K[,i], 2))));
  Fglob = apply(v -> lift(v), Vec(Fb));
  print("L: class number 1, signature ", bnf.sign, ", #gens L(S,2) = ", #gens, ", norm-square dim ", #K, ", Q(S,2) image dim ", rq, ", dim F_glob = ", #Fglob);
  Fel = vector(#Fglob, i, my(a = Mod(1, P)); for (j = 1, #gens, if (Fglob[i][j], a *= Mod(lift(gens[j]) * Mod(1, P), P))); a);   \\ elements of L
  Fel; };
\\ Hilbert-symbol coordinates at a prime pr of L
hb(a, b, pr) = (nfhilbert(bnf, lift(a), lift(b), pr) == -1);
mkbasis(pr) = { my(m = 2 + (pr.p == 2) * pr.e * pr.f, cands = List(), sel = List(), H, rk = 0, G);
  listput(cands, Mod(nfbasistoalg(bnf, pr.gen[2]), P)); foreach ([-1, 2, 3, 5, 7, 11, 13], q, listput(cands, Mod(q, P)));
  for (k = -6, 6, listput(cands, Mod(y + k, P)); listput(cands, Mod(y^2 + k, P)); listput(cands, Mod(y^2 + k*y + 1, P)); listput(cands, Mod(y^3 + k, P)));
  for (t = 1, 40, listput(cands, Mod(sum(i = 0, 5, (random(7) - 3) * y^i), P)));
  cands = select(cc -> cc != 0, Vec(cands));
  \\ full pairing matrix over the candidates; choose candidates whose pairing rows are independent
  H = Mod(matrix(#cands, #cands, a, b, hb(cands[a], cands[b], pr)), 2);
  if (matrank(H) < m, error(Str("candidates span only ", matrank(H), " of ", m, " dimensions at the prime above ", pr.p)));
  for (i = 1, #cands, if (#sel >= m, break); my(rows = concat(Vec(sel), [i]), Mr = matrix(#rows, #cands, a, b, H[rows[a], b])); if (matrank(Mr) > #sel, listput(sel, i)));
  my(B = vector(m, i, cands[sel[i]]));
  G = Mod(matrix(m, m, a, b, H[sel[a], sel[b]]), 2);
  [B, G^(-1)]; };
coords(a, B) = { my(sel = B[1], Ginv = B[2], h = Mod(vectorv(#sel, j, hb(a, sel[j], pr_cur)), 2)); lift(Ginv * h); };
resv(a, p) = { my(v = []); for (k = 1, #PR[p], pr_cur = PR[p][k]; v = concat(v, Vec(coords(a, BAS[p][k])))); vectorv(#v, i, v[i]); };

issq_p(r, p) = if (r == 0, 0, issquare(r + O(p^80)));
\\ is z = A + B sqrt(d) a square in Q_p(sqrt d)?  (d a non-square in Q_p)
issq_quad(A, B, d, p) = { if (B == 0, return(issq_p(A, p) || issq_p(A/d, p)));
  my(N = A^2 - d*B^2); if (N == 0 || !issq_p(N, p), return(0));
  my(m = sqrt(N + O(p^80)), t1 = (A + m)/2, t2 = (A - m)/2);
  (t1 != 0 && issquare(t1)) || (t2 != 0 && issquare(t2)); };
quadpoints(p, dlist, ulist, wlist, base, target) = { my(vecs = List(), n = 0, cur = base, rk0 = matrank(Mod(matconcat(base), 2)), rk = rk0, tried = 0);
  foreach (dlist, d, foreach (ulist, u, foreach (wlist, w, if (w == 0 || rk - rk0 >= target, next);
    my(fz = subst(f, x, u + w*z) % (z^2 - d), A = polcoef(fz, 0, z), B = polcoef(fz, 1, z));
    if (issq_quad(A, B, d, p), n++; my(v = resv(th^2 - 2*u*th + (u^2 - d*w^2), p), M = Mod(matconcat(concat(cur, [v])), 2));
      if (matrank(M) > rk, rk = matrank(M); cur = concat(cur, [v]); listput(vecs, v))))));
  [Vec(vecs), n, rk - rk0]; };
\\ local image from Q_p-points x = a/p^j: classes of x - theta
localimage(p, K, jmax) = { my(vecs = List(), base = 0, n = 0, prec = 60);
  for (j = 0, jmax, for (a = 0, p^(K + j) - 1, if (j > 0 && a % p == 0, next);
    my(xt = a / p^j, fx = subst(f, x, xt)); if (fx == 0, next);
    if (!issquare(fx + O(p^prec)), next);
    my(v = resv(xt - th, p)); if (base == 0, base = v, listput(vecs, lift(Mod(v - base, 2)))); n++));
  [Vec(vecs), n]; };
{
Fel = setup(-17*x^6 + 72*x^5 - 90*x^4 - 40*x^3 + 180*x^2 - 144*x + 40);
}
{
PR = vector(17); BAS = vector(17);
}
{
foreach (SPRIMES, p, PR[p] = idealprimedec(bnf, p); BAS[p] = vector(#PR[p], k, mkbasis(PR[p][k]));
  print("p = ", p, ": primes ", apply(pr -> [pr.e, pr.f], PR[p]), "  local square-class dims ", apply(B -> #B[1], BAS[p])));
}
{

foreach (SPRIMES, p, my(fa = factorpadic(f, p, 60), degs = vector(#fa[,1], i, poldegree(fa[i,1])), hasodd = vecmax(apply(dd -> dd % 2, degs)) == 1, t = #degs - 1 - hasodd, d = t + 2*(p == 2));

  print("p = ", p, ": local factor degrees ", degs, "  dim J(Q_p)[2] = ", t, "  dim J(Q_p)/2 = ", d, "  odd factor: ", hasodd, "  => expected dim of fake image = ", d - (1 - hasodd), if (hasodd, "", "  [assumes no common quadratic subfield of the local factors]")));
}
{

IMG = vector(17); DIAG = vector(17);
}
{
foreach (SPRIMES, p,
  Kp = if (p == 2, 4, if (p == 3, 3, 1));
  li = localimage(p, Kp, 2);
  Dq = if (p == 2, [-1, 2, 5], [p, if (p == 3, 2, 3)]);
  dl = if (p == 2, [-1, 2, -2, 5, -5, 10, -10], if (p == 3, [3, -1, -3], [17, 3, 51]));
  DIAG[p] = apply(q -> resv(Mod(q, P), p), Dq);
  sqd = select(dd -> vecmax(resv(Mod(dd, P), p)) == 0, dl);
  fa = factorpadic(f, p, 60); degs = vector(#fa[,1], ii, poldegree(fa[ii,1])); hasodd = vecmax(apply(dd -> dd % 2, degs)) == 1;
  tJ = #degs - 1 - hasodd; dJ = tJ + 2*(p == 2); oneminusone = !(hasodd || #sqd > 0);
  target = dJ - oneminusone;
  print("p = ", p, ": factors ", degs, ", (1,-1)_p nonzero: ", oneminusone, " => target dim of fake local image = ", target);
  base = concat(DIAG[p], li[1]); rk0 = matrank(Mod(matconcat(DIAG[p]), 2)); got = matrank(Mod(matconcat(base), 2)) - rk0;
  print("   rational points: ", li[2], ", image dim so far ", got);
  qp = [[], 0, 0];
  if (got < target,
    dep = if (p == 2, 3, 1); rng = if (p == 2, 24, 3*p);
    qp = quadpoints(p, dl, vector(2*rng*2^dep + 1, ii, (ii - 1 - rng*2^dep)/2^dep), vector(rng*2^dep, ii, ii/2^dep), base, target - got);
    got += qp[3]);
  print("   quadratic points tried/hit: ", qp[2], ", image dim now ", got, if (got == target, "  COMPLETE", "  INCOMPLETE"));
  IMG[p] = [concat(li[1], qp[1]), got, target]);
}
{


nF = #Fel; Sol = Mod(matid(nF), 2);
}
{
foreach (SPRIMES, p, my(Wp = matimage(Mod(matconcat(concat(IMG[p][1], DIAG[p])), 2)), nW = #Wp,
    R = Mod(matrix(#Wp[,1], nF, i, j, resv(Fel[j], p)[i]), 2), Kall = matker(matconcat([Wp, R])), Vp);
  Vp = if (#Kall == 0, matrix(nF, 0), matimage(matrix(nF, #Kall, i, j, Kall[nW + i, j])));

  if (#Sol == 0 || #Vp == 0, Sol = matrix(nF, 0),
    my(Ki = matker(matconcat([Sol, Vp]))); Sol = if (#Ki == 0, matrix(nF, 0), matimage(Sol * Ki[1..#Sol, ])));
  print("p = ", p, ": dim V_p = ", #Vp, "   dim of Selmer candidates so far = ", #Sol));
}
{
print("dim fake 2-Selmer group F_sel = ", #Sol, "   =>  dim Sel^2(J) = ", #Sol + 1, "  (the class (1,-1) = image of [P - iota P]),  rank J(Q) <= ", #Sol + 1);
}
\q
